---
- hosts: all
  become: true

  handlers:
    - name: restart containerd
      service:
        name: containerd
        state: restarted

  tasks:
  - include_tasks: k8s-base.yaml

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh
